// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelBatchProcess() {
  return window['go']['main']['App']['CancelBatchProcess']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveMapping(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveMapping'](arg1, arg2, arg3);
}

export function SaveResult(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveResult'](arg1, arg2, arg3, arg4, arg5);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function StartBatchProcess(arg1, arg2) {
  return window['go']['main']['App']['StartBatchProcess'](arg1, arg2);
}

export function SummarizeText(arg1, arg2, arg3) {
  return window['go']['main']['App']['SummarizeText'](arg1, arg2, arg3);
}
