// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function CancelBatchProcess():Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function LoadConfig():Promise<backend.AppConfig>;

export function SaveConfig(arg1:backend.AppConfig):Promise<void>;

export function SaveMapping(arg1:string,arg2:Array<string>,arg3:Array<string>):Promise<void>;

export function SaveResult(arg1:string,arg2:number,arg3:number,arg4:string,arg5:number):Promise<void>;

export function SelectDirectory():Promise<string>;

export function StartBatchProcess(arg1:backend.AppConfig,arg2:Array<string>):Promise<void>;

export function SummarizeText(arg1:string,arg2:string,arg3:string):Promise<string>;
